apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: allow-only-signed-profile-images
spec:
  images:
    - glob: "docker.io/admsup/profile**"
  authorities:
    - keyless:
        identities:
          - issuer: "https://token.actions.githubusercontent.com"
            subject: "https://github.com/admsup-i/profile/.github/workflows/main.yml@refs/heads/main"
