apiVersion: apps/v1
kind: Deployment
metadata:
  name: unsigned-profile-test
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unsigned-profile-test
  template:
    metadata:
      labels:
        app: unsigned-profile-test
    spec:
      imagePullSecrets:
        - name: dockerhub-pull
      containers:
        - name: profile
          image: docker.io/admsup/profile:unsigned-test
          ports:
            - containerPort: 8000
